version: "3"
services:
    calculator:
        deploy:
            replicas: 3
        image: pitachx/calculator:latest
        ports:
            - "8881:8080"
    redis:
        deploy:
            replicas: 1
        image: redis:latest

